version: "3"
services:
  # nginx:    
  #   build:
  #     context: ./nginx-reverse-proxy
  #     dockerfile: Dockerfile    
  #   container_name: nginx
  #   hostname: tech-interview.xaldigital.mx  
  #   ports:
  #     - "80:80"    
  #     - "443:443"    
  #   depends_on:
  #     - web-app      
  api:        
    build:
      context: ./api
      dockerfile: Dockerfile    
    container_name: api
    hostname: api.xaldigital.mx  
    ports:
      - "8081:8081"
    environment:
      - TZ=America/Tijuana
      - PORT=8081
      - DB_HOST=flight-db.xaldigital.mx
      - DB_USER=root
      - DB_PWD=holamundo123
      - DB_NAME=flight-db
      - ANSWER_ENDPOINT=https://api.stackexchange.com/2.2/search?order=desc&sort=activity&intitle=perl&site=stackoverflow
    depends_on:
      - flight-db
  flight-db:
    image: mysql:8.2.0
    container_name: flight-db
    hostname: flight-db.xaldigital.mx   
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: flight-db
      MYSQL_ROOT_PASSWORD: holamundo123  
volumes:
  mysql-data:      
