AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cv-api

  Sample SAM Template for cv-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CvApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
    Metadata:
      DockerTag: nodejs22.x-v1
      DockerContext: ./api
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CvApiFunction:
    Description: "My CV Lambda Function ARN"
    Value: !GetAtt CvApiFunction.Arn
  CvApiFunctionIamRole:
    Description: "Implicit IAM Role created for My CV function"
    Value: !GetAtt CvApiFunctionRole.Arn
